pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                echo 'check out code'
                checkout scmGit(branches: [[name: '*/development']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/harisparavoor/terraformwithjekinspipline.git']])
            }
        }
        stage ('terraform init'){ 
            steps { 
                 sh ('terraform init')       
            }
        }
        
        stage ('terraform action'){
            steps {
                echo "Terraform action is --> ${action}"
                sh ('terraform ${action} --auto-approve') 
            }
        }
    }
    
}